version: '2'
services:
    seminario2-mongodb:
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/seminario2/mongodb/:/data/db/
