version: '2'
services:
    seminario2-mongodb:
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        command: mongos --configdb seminario2-mongodb-config
    seminario2-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    seminario2-mongodb-config:
        image: mongo:3.2.10
        container_name: seminario2-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
